using ConsoleApplication.Algorithms;
using ConsoleApplication.Solver.Results;
using ConsoleApplication.Solver.Statistics;

namespace ConsoleApplication.Solver
{
    public interface ISolver
    {
        ISolverStatistics SolvingStatistics { get; }

        /// <summary>
        /// Solves TSP problem with given algorithm. 
        /// </summary>
        ISolverResult Solve(IAlgorithm tspSolvingAlgorithm);

        /// <summary>
        /// Solves TSP problem with given algorithm. Uses paths generated by other TSP solver. Starts
        /// from path first node.
        /// </summary>
        /// <param name="tspSolvingAlgorithm"></param>
        /// <param name="solverResult"> All paths generated in other solver </param>
        ISolverResult Solve(IAlgorithm tspSolvingAlgorithm, ISolverResult solverResult);

        /// <summary>
        /// Solves TSP problem with given algorithm. Uses paths generated by other TSP solver. 
        /// </summary>
        /// <param name="tspSolvingAlgorithm"></param>
        /// <param name="startNode"> Algorithm start node </param>
        ISolverResult Solve(IAlgorithm tspSolvingAlgorithm, int startNode);
    }
}