using System;
using ConsoleApplication.Algorithms;
using ConsoleApplication.Graphs;
using ConsoleApplication.Solver.SolverVisitor;

namespace ConsoleApplication.Solver
{
	public interface ISolver
	{
	    ISolverStatistics SolvingStatistics { get; }

	    /// <summary>
	    /// Solves TSP problem with given algorithm.
	    /// </summary>
		IPathAccumulator Solve(IAlgorithm tspSolvingAlgorithm);

	    /// <summary>
	    /// Solves TSP problem with given algorithm. Uses paths generated by other TSP solver.
	    /// Starts from path first node.
	    /// </summary>
	    /// <param name="tspSolvingAlgorithm"></param>
	    /// <param name="pathAccumulator"> All paths generated in other solver </param>
	    IPathAccumulator Solve(IAlgorithm tspSolvingAlgorithm, IPathAccumulator pathAccumulator);

	    /// <summary>
	    /// Solves TSP problem with given algorithm. Uses paths generated by other TSP solver.
	    /// </summary>
	    /// <param name="tspSolvingAlgorithm"></param>
	    /// <param name="startNode">Algorithm start node</param>
	    IPathAccumulator Solve(IAlgorithm tspSolvingAlgorithm, int startNode);
	}
}